SUBDIRs := data

PFs := RSNMST.FILE PRJMST.FILE EMPMST.FILE
DSPFs := MSTDSP.FILE
PGMs := PAYROLL.PGM

MSTDSP.FILE: $d/MSTDSP.DSPF
PAYROLL.PGM: $d/PAYROLL.PGM.RPGLE MSTDSP.FILE EMPMST.FILE PRJMST.FILE EMPMST.FILE