name: Bob Build Report

on:
  push:
    branches:
      - main

jobs:
  ibmi-build:
    environment: COMMON1
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - uses: actions/setup-node@v3
        with:
          node-version: 18
        
      - run: npm i -g @ibm/sourceorbit
    
      - run: npm i -g @ibm/ibmi-ci

      - name: Generate makefile
        run: so -bf bob

      - name: Deploy to IBM i
        run: | 
          ici \
            --cmd "mkdir -p './builds/ics_${GITHUB_HEAD_REF}'" \
            --rcwd "./builds/ics_${GITHUB_HEAD_REF}" \
            --push "." \
            --ignore --cl "CRTLIB PAYBOB" \
            --cmd "/QOpenSys/pkgs/bin/makei build -e BIN_LIB=PAYBOB"
        env:
          IBMI_HOST: ${{ secrets.IBMI_HOST }}
          IBMI_USER: ${{ secrets.IBMI_USER }}
          IBMI_PASSWORD: ${{ secrets.IBMI_PASSWORD }}
          IBMI_SSH_PORT: ${{ secrets.IBMI_SSH_PORT }}
